[features]
seeds = false
skip-lint = false
[programs.devnet]
pdas = "EPZNNVCNcJFYVqUJM6TcFMvzQ59mH2mdy4FnQVppJALn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/air/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
